framework:
    messenger:
        #default_bus: messenger.bus.default
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        #failure_transport: failed
        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            # Route your messages to the transports
            'App\Application\Contact\Message\CreateOrUpdateContactMessage': async
            # 🆕 Ajoute les messages manquants
            'App\Application\Organization\Message\CreateOrUpdateOrganizationMessage': async
            'App\Application\ContactOrganization\Message\ProcessChunkMessage': async
            'App\Application\Contact\Message\DeleteOldContactsMessage': sync  # Ce message peut rester en sync

when@test:
    framework:
        messenger:
            transports:
                # replace with your transport name here (e.g., my_transport: 'in-memory://')
                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
                async: 'in-memory://'
