framework:
    messenger:
        #default_bus: messenger.bus.default
        failure_transport: failed
        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection

        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            'App\Application\Common\Message\ProcessChunkMessage': async
            'App\Application\Contact\Message\DeleteOldContactsMessage': sync

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
